CREATE TABLE `tb_ins` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`value` TEXT NULL,
	`IN_Credit` INT(11) NULL DEFAULT NULL,
	`DT_Birth` DATE NULL DEFAULT NULL,
	`DTTM_Created` DATETIME NULL DEFAULT NULL,
	`AM_M_BS` DOUBLE(16,2) NULL DEFAULT NULL,
	`BL_Read` TINYINT(1) NULL DEFAULT NULL,
	INDEX `id` (`id`)
)
COMMENT='用来插入数据'
COLLATE='gbk_chinese_ci'
ENGINE=InnoDB
AUTO_INCREMENT=11
;
